# Generated by Django 5.1.7 on 2025-04-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaRelatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Registro_ANS', models.IntegerField()),
                ('CNPJ', models.CharField(max_length=15)),
                ('Nome_Fantasia', models.CharField(max_length=255)),
                ('Modalidade', models.CharField(max_length=255)),
                ('Logradouro', models.CharField(max_length=255)),
                ('Numero', models.CharField(max_length=20)),
                ('Complemento', models.CharField(max_length=255)),
                ('Bairro', models.CharField(max_length=255)),
                ('Cidade', models.CharField(max_length=255)),
                ('UF', models.CharField(max_length=3)),
                ('CEP', models.BigIntegerField()),
                ('DDD', models.CharField(max_length=4)),
                ('Telefono', models.CharField(max_length=20)),
                ('Fax', models.CharField(max_length=20)),
                ('Endereco_eletronico', models.CharField(max_length=255)),
                ('Representante', models.CharField(max_length=255)),
                ('Cargo_Representante', models.CharField(max_length=255)),
                ('Regiao_de_Comercializacao', models.IntegerField()),
            ],
            options={
                'db_table': 'relatorio_cadop',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
